### ISSUE TITLE
On CDH 5.3.0, can I just import maven deps and build an uber jar?

### ISSUE THREAD

**Issue by drocsid** [cloudera-labs/SparkOnHBase#13]
I stumbled upon this projects maven repository and thought I could use it since I'm running a CDH 5.3.0 cluster. Then I imported the maven deps and built an uber jar similar to the pom.xml at the gist below

https://gist.github.com/drocsid/c545934b2d505461807df1005b89016c

I tried to run it in yarn cluster mode, as shown in the above shell script. but then I read https://github.com/cloudera-labs/SparkOnHBase/issues/6, which says it only runs in yarn-client mode.

I'm trying to use hbContext.streamBulkPut along with content I'm getting from my kafka-cluster. 

Can I expect my uber jar, `/home/colin.williams/ad-export-1.0-SNAPSHOT.jar`, built using mvn package, on the pom.xml described above to run the application or do I still need to use the 

--jars /opt/cloudera/parcels/CDH/lib/zookeeper/zookeeper-3.4.5-cdh5.3.1.jar,/opt/cloudera/parcels/CDH/lib/hbase/lib/guava-12.0.1.jar,/opt/cloudera/parcels/CDH/lib/hbase/lib/protobuf-java-2.5.0.jar,/opt/cloudera/parcels/CDH/lib/hbase/hbase-protocol.jar,/opt/cloudera/parcels/CDH/lib/hbase/hbase-client.jar,/opt/cloudera/parcels/CDH/lib/hbase/hbase-common.jar,/opt/cloudera/parcels/CDH/lib/hbase/hbase-hadoop2-compat.jar,/opt/cloudera/parcels/CDH/lib/hbase/hbase-hadoop-compat.jar,/opt/cloudera/parcels/CDH/lib/hbase/hbase-server.jar,/opt/cloudera/parcels/CDH/lib/hbase/lib/htrace-core.jar 

Similarly, do I need to 
--driver-java-options -Dspark.executor.extraClassPath=/opt/cloudera/parcels/CDH/lib/hbase/lib/*

Or does my spark-submit script look sufficient?

@tmalaska: I realized you've moved on from this old base, but can you offer a little assistance, so my effort isn't wasted?

**Comment by drocsid** [comment]
I've changed my launcher script a little since my post above, and from yarn the application succeeds. I've tried both client and cluster modes:

export HADOOP_CONF_DIR=/etc/hadoop/conf

spark-submit \
  --class com.sdl.si.sap.authordetails.KafkaToAD \
  --master yarn \
  --deploy-mode client \
  --num-executors 2 \
  --driver-memory 512m \
  --executor-memory 4096m \
  --executor-cores 3 \
  --queue default \
  --conf spark.yarn.submit.waitAppCompletion=true \
  --conf spark.app.name="Kafka To AD" \
  --conf spark.streaming.receiver.maxRate=1000 \
  --conf spark.streaming.concurrentJobs=2 \
  --conf spark.eventLog.dir="hdfs:///user/spark/applicationHistory" \
  --conf spark.eventLog.enabled=true \
  --conf spark.eventLog.overwrite=true \
  --conf spark.yarn.historyServer.address="http://us3sm2utl03.comp.prod.local:18080/" \
  --conf spark.yarn.dist.files=hdfs:///user/colin.williams/ad-export-1.0-SNAPSHOT.jar \
  /home/colin.williams/ad-export-1.0-SNAPSHOT.jar 

When I look at the application logs, I only see:

yarn logs -applicationId application_1453754997414_601888


Container: container_1453754997414_601888_01_000002 on us3sm2hb022r07.comp.prod.local_8041
============================================================================================
LogType: stderr
LogLength: 495
Log Contents:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/zookeeper/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data3/yarn/local/usercache/colin.williams/filecache/45/authordetails-export-1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

LogType: stdout
LogLength: 0
Log Contents:



Container: container_1453754997414_601888_01_000001 on us3sm2hb029r08.comp.prod.local_8041
============================================================================================
LogType: stderr
LogLength: 495
Log Contents:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/zookeeper/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data6/yarn/local/usercache/colin.williams/filecache/40/authordetails-export-1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

LogType: stdout
LogLength: 0
Log Contents:



Container: container_1453754997414_601888_01_000003 on us3sm2hb031r07.comp.prod.local_8041
============================================================================================
LogType: stderr
LogLength: 495
Log Contents:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/zookeeper/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data2/yarn/local/usercache/colin.williams/filecache/45/authordetails-export-1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

LogType: stdout
LogLength: 0
Log Contents:


I'm going to post my application code here in a few minutes.

**Comment by drocsid** [comment]
This is what my applications main class looks like:

https://gist.github.com/drocsid/b0efa4ff6ff4a7c3c8bb56767d0b6877

**Comment by drocsid** [comment]
I believe the yarn node-manager logs might be telling me it's a classpath issue. Then the question above regarding jars seems relevant. I'm basing this on:

2016-04-25 13:53:34,876 WARN org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor: Exit code from container container_1453754997414_618742_01_000002 is : 1
2016-04-25 13:53:34,876 WARN org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor: Exception from container-launch with container ID: container_1453754997414_618742_01_000002 and exit code: 1
ExitCodeException exitCode=1:
  at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
  at org.apache.hadoop.util.Shell.run(Shell.java:455)
  at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:702)
  at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:197)
  at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:299)
  at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:81)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor: Exception from container-launch.
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor: Container id: container_1453754997414_618742_01_000002
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor: Exit code: 1
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor: Stack trace: ExitCodeException exitCode=1:
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at org.apache.hadoop.util.Shell.run(Shell.java:455)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:702)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:197)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:299)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:81)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
2016-04-25 13:53:34,876 INFO org.apache.hadoop.yarn.server.nodemanager.ContainerExecutor:   at java.lang.Thread.run(Thread.java:745)
2016-04-25 13:53:34,876 WARN org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch: Container exited with a non-zero exit code 1
2016-04-25 13:53:34,883 INFO org.apache.hadoop.yarn.server.nodemanager.containermanager.container.Container: Container container_1453754997414_618742_01_000002 transitioned from RUNNING to EXITED_WITH_FAILURE
2016-04-25 13:53:34,883 INFO org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch: Cleaning up container container_1453754997414_618742_01_000002

**Comment by drocsid** [comment]
I've changed my spark submit and provided the jars as suggested by the author in the README. When I launch the application, it runs for 10-20 seconds, and the application completes successfully according to YARN. However I cannot find a debugging message in STDOUT as the first line in the main method.

`
#!/usr/bin/env bash
export SPARK_CONF_DIR=/home/colin.williams/spark
export HADOOP_CONF_DIR=/etc/hadoop/conf
export HADOOP_CLASSPATH=/etc/hbase/conf:/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/*:/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/hbase-protocol-0.98.6-cdh5.3.0.jar

spark-submit \
--class com.example.ad.KafkaToAD \
--master yarn \
--deploy-mode client \
--num-executors 2 \
--driver-memory 512m \
--executor-memory 4096m \
--executor-cores 3 \
--queue search \
--jars /home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/zookeeper/zookeeper-3.4.5-cdh5.3.0.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/guava-12.0.1.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/protobuf-java-2.5.0.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-protocol.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-client.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-common.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-hadoop2-compat.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-hadoop-compat.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-server.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/htrace-core.jar \
--conf spark.yarn.submit.waitAppCompletion=true \
--conf spark.app.name="Kafka To AD" \
--conf spark.streaming.receiver.maxRate=1000 \
--conf spark.streaming.concurrentJobs=2 \
--conf spark.eventLog.dir="hdfs:///user/spark/applicationHistory" \
--conf spark.eventLog.enabled=true \
--conf spark.eventLog.overwrite=true \
--conf spark.yarn.historyServer.address="http://utl03.comp.prod.local:18080/" \
--conf spark.yarn.dist.files=hdfs:///user/colin.williams/ad-export-1.0-SNAPSHOT-uber.jar \
--driver-java-options -Dspark.executor.extraClassPath=/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/* \
/home/colin.williams/ad-export-1.0-SNAPSHOT-uber.jar "hello world"
`

**Comment by drocsid** [comment]
I think it's appropriate that I follow the README instructions, and try to build and run the examples. Then I will give this a shot again.

**Comment by drocsid** [comment]
I'm now trying to run the example on CDH 5.3.0. I've created the following launch script, based on @tmalaska readme:

export HADOOP_CONF_DIR=/etc/hadoop/conf
export HADOOP_CLASSPATH=/opt/cloudera/parcels/CDH/lib/hbase/lib/*:/opt/cloudera/parcels/CDH/lib/hbase/lib/hbase-protocol-0.98.6-cdh5.3.0.jar:/etc/hbase/conf
spark-submit \
  --jars /home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/zookeeper/zookeeper-3.4.5-cdh5.3.0.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/guava-12.0.1.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/protobuf-java-2.5.0.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-protocol.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-client.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-common.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-hadoop2-compat.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-hadoop-compat.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/hbase-server.jar,/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/htrace-core.jar \
  --class com.cloudera.spark.hbase.example.HBaseBulkPutExample \
  --master yarn \
  --deploy-mode client \
  --executor-memory 512M \
  --num-executors 4 \
  --driver-java-options -Dspark.executor.extraClassPath=/home/colin.williams/CDH-5.3.0-1.cdh5.3.0.p0.30/lib/hbase/lib/* \
  --queue search \
  /home/colin.williams/SparkHBase.jar t1 c \



Furthermore, I created the table in the hbase shell, and built the jar from this project branch cdh5-0.0.2. I am going through this further, looking through my configurations.

It does start the yarn client application, but it just hangs hangs in Yarn, and I can't find any useful logging messages.

**Comment by drocsid** [comment]
It appears the HBaseBulkPutExample is working. I had an hbase configuration issue. Then I'm going to look at the example source and refactor as necessary.

**Comment by drocsid** [comment]
Any insight from the author would be appreciated.

**Comment by drocsid** [comment]
I'm now able to view what I think is related to each rdd "batch: or duration:
```
-------------------------------------------
Time: 1461862168000 ms
-------------------------------------------

-------------------------------------------
Time: 1461862168000 ms
-------------------------------------------
```

I've tried printing out some debugging information for the streams, however, I cannot find them anywhere in the logs. I would assume that an exception should be thrown if there are connection issues, but the application appears to still be running. Then it would be nice if I had a way to debug it. 

```
dstream.print();
protobufPairStream.print();
valueStream.print();



```

**Comment by drocsid** [comment]
After some more effort I'm consuming messages for awhile, and then

```
Exception in thread "Thread-38" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 606, us3sm2hb028r07.comp.prod.local): kafka.common.ConsumerRebalanceFailedException: KafkaToAD_us3sm2hb028r07.comp.prod.local-1461884129503-cf1c18fd can't rebalance after 4 retries
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(Unknown Source)
	at kafka.consumer.ZookeeperConsumerConnector.kafka$consumer$ZookeeperConsumerConnector$$reinitializeConsumer(Unknown Source)
	at kafka.consumer.ZookeeperConsumerConnector.consume(Unknown Source)
	at kafka.consumer.ZookeeperConsumerConnector.createMessageStreams(Unknown Source)
	at org.apache.spark.streaming.kafka.KafkaReceiver.onStart(KafkaInputDStream.scala:111)
	at org.apache.spark.streaming.receiver.ReceiverSupervisor.startReceiver(ReceiverSupervisor.scala:121)
	at org.apache.spark.streaming.receiver.ReceiverSupervisor.start(ReceiverSupervisor.scala:106)
	at org.apache.spark.streaming.scheduler.ReceiverTracker$ReceiverLauncher$$anonfun$8.apply(ReceiverTracker.scala:277)
	at org.apache.spark.streaming.scheduler.ReceiverTracker$ReceiverLauncher$$anonfun$8.apply(ReceiverTracker.scala:269)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1314)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1314)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1214)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1203)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1202)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1202)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:696)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1420)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by drocsid** [comment]
It appears that I'm able to use the streamingBulkPut class now. I still wonder about build issues but right now I'm having issues with the kafka consumer.

**Comment by drocsid** [comment]
Not getting more than 2500 requests per second via hbase console for 8 executors, currently unsure where the bottleneck is.

**Comment by drocsid** [comment]
After reading the spark-hbase docs in the hbase book, then it appears that StreamingBulkPut is the bottleneck. It just can't keep up with the rest of the streaming process. Then I'm going to look at trying to somehow perform a bulk load of the content into hbase.

**Comment by drocsid** [comment]
I'm not sure the num executors setting was applied. I've set total-executor-cores. I've been able to make this work well enough for my purposes. Still haven't built an uber jar, but maybe I can do this later.
